export const PRODUCT = {
  FETCH_REQUEST: {
    GET_ONE: "SH_PRODUCT_FETCH_REQUEST_GET_ONE",
    GET: "SH_PRODUCT_FETCH_REQUEST_GET",
    POST: "SH_PRODUCT_FETCH_REQUEST_POST",
    PUT: "SH_PRODUCT_FETCH_REQUEST_PUT",
    DELETE: "SH_PRODUCT_FETCH_REQUEST_DELETE"
  },
  FETCH_SUCCESS: {
    GET_ONE: "SH_PRODUCT_FETCH_SUCCESS_GET_ONE",
    GET: "SH_PRODUCT_FETCH_SUCCESS_GET",
    POST: "SH_PRODUCT_FETCH_SUCCESS_POST",
    PUT: "SH_PRODUCT_FETCH_SUCCESS_PUT",
    DELETE: "SH_PRODUCT_FETCH_SUCCESS_DELETE"
  },
  FETCH_FAILURE: {
    GET_ONE: "SH_PRODUCT_FETCH_FAILURE_GET_ONE",
    GET: "SH_PRODUCT_FETCH_FAILURE_GET",
    POST: "SH_PRODUCT_FETCH_FAILURE_POST",
    PUT: "SH_PRODUCT_FETCH_FAILURE_PUT",
    DELETE: "SH_PRODUCT_FETCH_FAILURE_DELETE"
  },
  FETCH_END: {
    GET_ONE: "SH_PRODUCT_FETCH_END_GET_ONE",
    GET: "SH_PRODUCT_FETCH_END_GET",
    POST: "SH_PRODUCT_FETCH_END_POST",
    PUT: "SH_PRODUCT_FETCH_END_PUT",
    DELETE: "SH_PRODUCT_FETCH_END_DELETE"
  },
  PHOTO: {
    FETCH_REQUEST: {
      GET: "SH_PHOTO_FETCH_REQUEST_GET",
      POST: "SH_PHOTO_FETCH_REQUEST_POST",
      DELETE: "SH_PHOTO_FETCH_REQUEST_DELETE"
    },
    FETCH_SUCCESS: {
      GET: "SH_PHOTO_FETCH_SUCCESS_GET",
      POST: "SH_PHOTO_FETCH_SUCCESS_POST",
      DELETE: "SH_PHOTO_FETCH_SUCCESS_DELETE"
    },
    FETCH_FAILURE: {
      GET: "SH_PHOTO_FETCH_FAILURE_GET",
      POST: "SH_PHOTO_FETCH_FAILURE_POST",
      DELETE: "SH_PHOTO_FETCH_FAILURE_DELETE"
    },
    FETCH_END: {
      GET: "SH_PHOTO_FETCH_END_GET",
      POST: "SH_PHOTO_FETCH_END_POST",
      DELETE: "SH_PHOTO_FETCH_END_DELETE"
    },
  }
};

export const CATEGORY = {
  FETCH_REQUEST: {
    GET: "SH_CATEGORY_FETCH_REQUEST_GET",
    POST: "SH_CATEGORY_FETCH_REQUEST_POST",
    PUT: "SH_CATEGORY_FETCH_REQUEST_PUT",
    DELETE: "SH_CATEGORY_FETCH_REQUEST_DELETE"
  },
  FETCH_SUCCESS: {
    GET: "SH_CATEGORY_FETCH_SUCCESS_GET",
    POST: "SH_CATEGORY_FETCH_SUCCESS_POST",
    PUT: "SH_CATEGORY_FETCH_SUCCESS_PUT",
    DELETE: "SH_CATEGORY_FETCH_SUCCESS_DELETE"
  },
  FETCH_FAILURE: {
    GET: "SH_CATEGORY_FETCH_FAILURE_GET",
    POST: "SH_CATEGORY_FETCH_FAILURE_POST",
    PUT: "SH_CATEGORY_FETCH_FAILURE_PUT",
    DELETE: "SH_CATEGORY_FETCH_FAILURE_DELETE"
  },
  FETCH_END: {
    GET: "SH_CATEGORY_FETCH_END_GET",
    POST: "SH_CATEGORY_FETCH_END_POST",
    PUT: "SH_CATEGORY_FETCH_END_PUT",
    DELETE: "SH_CATEGORY_FETCH_END_DELETE"
  }
};

export const USER = {
  FETCH_REQUEST: {
    GET: "SH_USER_FETCH_REQUEST_GET",
    PUT: "SH_USER_FETCH_REQUEST_PUT",
  },
  FETCH_SUCCESS: {
    GET: "SH_USER_FETCH_SUCCESS_GET",
    PUT: "SH_USER_FETCH_SUCCESS_PUT",
  },
  FETCH_FAILURE: {
    GET: "SH_USER_FETCH_FAILURE_GET",
    PUT: "SH_USER_FETCH_FAILURE_PUT",
  },
  FETCH_END: {
    GET: "SH_USER_FETCH_END_GET",
    PUT: "SH_USER_FETCH_END_PUT",
  }
};


export const ORDER = {
  FETCH_REQUEST: {
    GET: "SH_ORDER_FETCH_REQUEST_GET",
    PUT: "SH_ORDER_FETCH_REQUEST_PUT",
  },
  FETCH_SUCCESS: {
    GET: "SH_ORDER_FETCH_SUCCESS_GET",
    PUT: "SH_ORDER_FETCH_SUCCESS_PUT",
  },
  FETCH_FAILURE: {
    GET: "SH_ORDER_FETCH_FAILURE_GET",
    PUT: "SH_ORDER_FETCH_FAILURE_PUT",
  },
  FETCH_END: {
    GET: "SH_ORDER_FETCH_END_GET",
    PUT: "SH_ORDER_FETCH_END_PUT",
  }
};